# WRITE A PROGRAM TO DETECT DOUBLE SPACE IN A STRING
 
a = "EMBRACING THE  PEACE"
print(a.find ("  ")) # NOTE: IF THERE IS NO DOUBLE SPACE IT WILL GIVE -1 IN OUTPUT
                    #  NOTE: WE CAN ALSO FIND THE LETTERS IN ANY WORD FROM THIS METHOD

