# WHAT WILL BE THE LENGTH OF THE FOLLOWING SET 

s = set()
s.add(20)
s.add(20.0)
s.add("20")

print(len(s)) # THE OUTPUT IS 2 BECAUSE 20 AND 20.0 ARE SAME NUMERICAL VALUES THEIR 
              # DATATYPE MAYBE DIFFERENT FROM EACH OTHER BUT 2 IS ALSO CONSIDERED AS 2.O
              # IN PYTHON AND 2.0 IS CONSIDERED AS 2 IN PYTHON 
               