# WHAT KIND OF SET IT IS

s = {}

print(type(s)) # TYPE IS DICTIONARY IT IS NOT A SET AS WE HAVE STUDIED PREVIOUSLY IN THIS
               # CHAPTER THAT IF WE USE CURLY BRACKETS IT WILL CONSIDERED AS AN EMPTY DICT
               # FOR AN EMPTY SET IT IS NECESSARY TO USE ROUND BRACKETS
                 