# CREATE AN EMPTY DICTIONARY AND ALLOW 4 FRIENDS TO WRITE THEIR FAVOURITE COUNTRY AS VALUE
# AND THEIR NAMES AS KEY 

d = {}

name = input("ENTER FRIEND NAME: ")
country = input("ENTER COUNTRY NAME:")
d.update({name : country})

name = input("ENTER FRIEND NAME: ")
country = input("ENTER COUNTRY NAME:")
d.update({name : country})

name = input("ENTER FRIEND NAME: ")
country = input("ENTER COUNTRY NAME:")
d.update({name : country})

name = input("ENTER FRIEND NAME: ")
country = input("ENTER COUNTRY NAME:")
d.update({name : country})

print(d) 

# Q: IF THE NAME OF TWO FRIENDS ARE SAME WHAT WILL HAPPEN?
# ANSWER: NAMES CANNOT BE SAME AND IF THEY ARE IT WILL TERMINATE THE FIRST NAME AND WILL SHOW
# THE LAST ENTERED NAME (KEYS CANNOT BE SAME)
# Q: IF THE COUNTRIES ARE SAME WHAT WILL HAPPEN?
# ANSWER: IF THE COUNTRIES ARE SAME NOTHNG WILL HAPPEN BECAUSE VALUES CAN BE SAME 
