# CAN YOU CHANGE THE VALUE OF A LIST WHICH IS CONTAINED IN A SET?

# NO WE CANNOT CHANGE THE VALUE OF A LIST WHICH IS CONTAINED IN A SET
# BECAUSE SETS ARE UNIDEXED THERE IS NO INDEXING IN SETS 
# YOU CANNOT EVEN HAVE A LIST IN A SET . 
