# DICTIONARIES METHODS IN PYTHON

marks = {
    "Shahaan" : 95,  # ON THE LEFT SIDE WE HAVE KEYS 
    "Dayyan" : 94,   # ON THE RIGHT SIDE WE HAVE VALUES 
    "Sudais" : 90,
      0  : "Khadim" # INTEGERS CAN ALSO E USED IN KEYS  
}

# print(marks.items()) # PRINTS THE ITEMS FROM OUR DICTIONARY, ITEMS ARE COMBINATION OF KEYS, VALUES
# print(marks.keys()) # PRINTS THE KEYS OF DICTIONARY
# print(marks.values()) #PRINTS THE VALUES OF DICTIONARY
# NOTE: AS WE KNOW DICTIONARIES ARE MUTABLE WHICH MEANS WE CAN THE VALUE OF THEM BY FOLLOWING METHOD
# marks.update({"Shahaan" : 90}) # MARKS OF SHAHAAN ARE UPDATED FROM 95 TO 90 WE CAN ALSO ADD ANOTHER KEY AND VALUE
# print(marks["Shahaan"])
# ANOTHER TRICKY METHOD OF DICTIONARY IS "marks.get". IT SEEMS LIKE THE SAME AS "prints(marks["Shahaan"])" BUT ITS NOT 
# print(marks.get("Shahaan")) # AS YOU CAN SEE IT PRINTS THE VALUE OF SHAHAAN BUT HERES THE TWIST 
# print(marks["Shahaan"]) # IT ALSO PRINTS THE VALUE OF SHAHAAN THEN WHY USE "marks.get" METHOD LEMME TELL YOU FROM EXAMPLE
print(marks.get("Shahaan2")) # AS YOU SEE IF I TRY TO RECALL A VALUE FROM DICTIONARY THAT IS NOT MENTIONED THERE IT GIVES ME NONE AS AN OUTPUT
print(marks["Shahaan2"]) # WHERE AS IN THIS METHOD IT GIVES US AN ERROR 
