# SETS

# s1 = {1, 4, 7, 8} 

# print(s1, type(s1)) 
# # AS WE KNOW DICTIONARIES ARE ALSO CREATED BY CURLY BRACKETS SO HOW WILL WE CREATE AN EMPTY SET
# s = {} 
# print(type(s)) # IT IS DECLARED AS AN EMPTY DICTIONARY SO WE USE FOLLOWING METHOD FOR EMPTY SET

# s = set() # WITH ROUND BRACKETS FOR EMPTY SETS 
# print(type(s)) 
s1 = {1, 4, 7, 8, 1, 4} # REPETITIONS ARE NOT ALLOWED IT WILL PRINT THE REPEATED VALUE AS ONE  
print(s1) # UNORDERED VALUES ARE PRINTED 
