# DIFFERENT METHODS IN SETS 
 
s = {1, 4, 7, 8, 1, 4, "Artist"} # WE CAN ALSO USE OTHER DATA TYPE ELEMENTS IN SETS 
print(s)

s.add(600) # ADDS 600 IN THE SET
print(s) # WE CANNOT CHANGE ITEMS IN SETS 
         # SETS ARE UNINDEXED
         # SETS CANNOT CONTAIN DUPLICATE VALUES 
print(len(s)) # AS YOU CAN SEE WE HAVE TOTAL 8 ELEMENTS IN SET UT OUTPUT IS 6 BECAUSE 1 & 4 ARE REPEATED      

s.remove("Artist") # REMOVES AN ELEMENT FROM SET
print(s) 

s.pop() # REMOVES A RANDOM ELEMENT FROM OUR SET
print(s) 

s.clear() # EMPTIES OUR SET 's'

