# CONDITIONAL STATEMENTS 

a = int(input("ENTER YOUR AGE:"))

if(a>=18):
    print("YOU'RE ELIGILE FOR DRIVING LICENSE \n YOU CAN APPLY")

else:
    print("YOU'RE NOT ELIGIBLE FOR DRIVING LICENSE \n WAIT TILL YOU'RE 18" )

# ELIF CONDITION

a = int(input("ENTER YOUR AGE:"))

if(a>=18):
    print("YOU'RE ELIGILE FOR DRIVING LICENSE \n YOU CAN APPLY")

elif(a<=0):
    print("YOU'VE ENTERED AN INVALID AGE")

else:
    print("YOU'RE NOT ELIGIBLE FOR DRIVING LICENSE \n WAIT TILL YOU'RE 18" )
# WE CAN HAVE MULTIPLE ELIF CONDITIONS 